language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

apt_packages:
  - libidn11-dev

notifications:
  email:
    on_success: change
    on_failure: change
