// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// puny_encode
std::vector < std::string > puny_encode(CharacterVector domains);
RcppExport SEXP punycode_puny_encode(SEXP domainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type domains(domainsSEXP);
    __result = Rcpp::wrap(puny_encode(domains));
    return __result;
END_RCPP
}
// puny_decode
std::vector < std::string > puny_decode(CharacterVector domains);
RcppExport SEXP punycode_puny_decode(SEXP domainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type domains(domainsSEXP);
    __result = Rcpp::wrap(puny_decode(domains));
    return __result;
END_RCPP
}
// puny_tld_check
std::vector < bool > puny_tld_check(CharacterVector domains);
RcppExport SEXP punycode_puny_tld_check(SEXP domainsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type domains(domainsSEXP);
    __result = Rcpp::wrap(puny_tld_check(domains));
    return __result;
END_RCPP
}
