# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Encode punycode domains to IDNA
#' @description Converts punycode domains to IDNA
#'
#' @param domains IDNA domains
#'
#' @return a vector of IDNA domains
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html}
#'
#' @examples
#' \dontrun{
#' }
#' @export
puny_encode <- function(domains) {
    .Call('punycode_puny_encode', PACKAGE = 'punycode', domains)
}

#' @title Decode IDNA domains to punycode
#' @description Converts IDNA domains to punycode
#'
#' @param domains IDNA domains
#'
#' @return a vector of punycode domains
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html}
#'
#' @examples
#' \dontrun{
#' }
#' @export
puny_decode <- function(domains) {
    .Call('punycode_puny_decode', PACKAGE = 'punycode', domains)
}

