# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Encode Punycode domains to IDNA
#' @description Converts Punycode domains to IDNA.
#'
#' @param domains character vector of IDNA domains
#'
#' @return a character vector of IDNA domains
#'
#' @note If there are any issues during the conversion, \code{"Invalid"} will
#'       be the value returned.
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html} and
#'     \url{http://www.faqs.org/rfcs/rfc3490.html} and
#'     \url{http://www.gnu.org/software/libidn/}
#'
#' @examples
#' puny_encode(c("xn------qpeiobbci9acacaca2c8a6ie7b9agmy.net",
#'               "xn----peurf0asz4dzaln0qm161er8pd.biz"))
#' @export
puny_encode <- function(domains) {
    .Call('punycode_puny_encode', PACKAGE = 'punycode', domains)
}

#' @title Decode IDNA domains to Punycode
#' @description Converts IDNA domains to Punycode
#'
#' @param domains character vector of IDNA domains
#'
#' @return a character vector of Punycode domains
#'
#' @note If there are any issues during the conversion, \code{"Invalid"} will
#'       be the value returned.
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html} and
#'     \url{http://www.faqs.org/rfcs/rfc3490.html} and
#'     \url{http://www.gnu.org/software/libidn/}
#'
#' @examples
#' puny_decode(c("новый-год.com", "טיול-לפיליפינים."))
#' @export
puny_decode <- function(domains) {
    .Call('punycode_puny_decode', PACKAGE = 'punycode', domains)
}

#' @title Check domains for validity
#' @description Check international domain names for charset validity
#'
#' @param domains character vector of domains
#'
#' @return a logical vector
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html} and
#'     \url{http://www.faqs.org/rfcs/rfc3490.html} and
#'     \url{http://www.gnu.org/software/libidn/}
#'
#' @examples
#' puny_tld_check(c("gr€€n.no", "rudis.net"))
#' @export
puny_tld_check <- function(domains) {
    .Call('punycode_puny_tld_check', PACKAGE = 'punycode', domains)
}

