# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Encode punycode domains to IDNA
#' @description Converts punycode domains to IDNA
#'
#' @param domains character vector of IDNA domains
#'
#' @return a character vector of IDNA domains
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html}
#'
#' @examples
#' puny_encode("xn------qpeiobbci9acacaca2c8a6ie7b9agmy.net")
#' @export
puny_encode <- function(domains) {
    .Call('punycode_puny_encode', PACKAGE = 'punycode', domains)
}

#' @title Decode IDNA domains to punycode
#' @description Converts IDNA domains to punycode
#'
#' @param domains character vector of IDNA domains
#'
#' @return a character vector of punycode domains
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html}
#'
#' @examples
#' puny_decode("новый-год.com")
#' @export
puny_decode <- function(domains) {
    .Call('punycode_puny_decode', PACKAGE = 'punycode', domains)
}

#' @title Check domains for validity
#' @description Check international domain names for charset validity
#'
#' @param domains character vector of domains
#'
#' @return a logical vector
#'
#' @seealso \url{http://www.faqs.org/rfcs/rfc3492.html}
#'
#' @examples
#' puny_tld_check("gr€€n.no")
#' @export
puny_tld_check <- function(domains) {
    .Call('punycode_puny_tld_check', PACKAGE = 'punycode', domains)
}

